version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    env_file:
      - .env
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - price-network

  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d $${DB_NAME} -U $${DB_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build: .
    command: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    networks:
      - price-network

  api:
    build: ./api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    networks:
      - price-network

  monitoring:
    build: ./monitoring
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      api:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    networks:
      - price-network

  bot:
    build: ./bot
    env_file:
      - .env
    depends_on:
      - api

networks:
  price-network:
    driver: bridge